# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a264e7bea8615b52d7c921905f28e791dec5956b36704a07e22b8d7b5976a6f735e5f6bbb305cea0ead20cce822afbdf660fea07c87185d20f28b23f4c2bc92

test:
  secret_key_base: 1fc0c1e28093fdac3f3a1639ef6cd3f8995a3321b9b79724366c00bf2f1c28d0667c15720a9adf8c6795dabf4051dd74df9e3fd0d8bd43bcfdc337b812a55035

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
